<?php

namespace Kadher\CigogneBundle\Repository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAgences($id){
        $qb = $this->_em->createQueryBuilder();
  
        $qb->select('a')->from('KadherCigogneBundle:Agence','a');
        $qb->innerJoin('a.user','u')->where('u.id = :id')->setParameter('id', $id);
        
        return $qb->getQuery()->getArrayResult();
  
    }
}
