<?php

namespace Kadher\CigogneBundle\Repository;

/**
 * CommerceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommerceRepository extends \Doctrine\ORM\EntityRepository
{
}
