<?php

namespace Kadher\CigogneBundle\Repository;

/**
 * PartenaireirenaireeeeeireaiireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireirenaireeeeeireaiireRepository extends \Doctrine\ORM\EntityRepository
{
}
