<?php

namespace Kadher\CigogneBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

  public function isNumberExist($number){
    $qb = $this->_em->createQueryBuilder();

    $qb->select('u')->from('KadherCigogneBundle:User','u');
    $qb->where('u.numero = :number')->setParameter('number', $number);
    return $qb->getQuery()->getResult();
  }


  public function isEmailExist($email){
    $qb = $this->_em->createQueryBuilder();

    $qb->select('u')->from('KadherCigogneBundle:User','u');
    $qb->where('u.email = :email')->setParameter('email', $email);
    return $qb->getQuery()->getResult();
  }


  public function isEmailExist1($email){
    $qb = $this->_em->createQueryBuilder();

    $qb->select('u')->from('KadherCigogneBundle:User','u');
    $qb->where('u.email = :email')->setParameter('email', $email);
    if($qb->getQuery()->getOneOrNullResult() != null)
    return $qb->getQuery()->getSingleResult();
    else 
    return null;
  }


  public function findMyUser($email){
    $qb = $this->_em->createQueryBuilder();

    $qb->select('u')->from('KadherCigogneBundle:User','u');
    $qb->where('u.email = :email')->setParameter('email', $email);
    return $qb->getQuery()->getArrayResult();
  }



  public function findMyUser1($email){
    $qb = $this->_em->createQueryBuilder();

    $qb->select('u')->from('KadherCigogneBundle:User','u');
    $qb->where('u.email = :email')->setParameter('email', $email);
    if($qb->getQuery()->getResult() == null)
      return null;
    else
      return $qb->getQuery()->getArrayResult();
  }
}
