kadher_rest_homepage:
    path:     /
    defaults: { _controller: KadherRestBundle:Default:index }

kadher_rest_test:
    path:     /test
    defaults: { _controller: KadherRestBundle:Default:test }


kadher_rest_verify_number:
    path:     /verify-number/{number}
    defaults: { _controller: KadherRestBundle:Default:verifyNumber }


kadher_rest_verify_email:
    path:     /verify-email/{email}
    defaults: { _controller: KadherRestBundle:Default:verifyEmail }


kadher_rest_sign_up:
    path:     /sign-up
    defaults: { _controller: KadherRestBundle:Default:signUp }


kadher_rest_sign_in:
    path:     /sign-in
    defaults: { _controller: KadherRestBundle:Default:signIn }


kadher_rest_reset_pass:
    path:     /reset-pass/{email}/{code}
    defaults: { _controller: KadherRestBundle:Default:resetPass }


kadher_rest_reset_pass_done:
    path:     /reset-pass-done/{email}/{pass}
    defaults: { _controller: KadherRestBundle:Default:resetPassDone }


kadher_rest_get_agence:
    path:     /get-agence/{id}
    defaults: { _controller: KadherRestBundle:Default:getAgence }